openstack-cluster:
  cloudCredentialsSecretName: worker-cloud-credentials

  kubernetesVersion: "1.31.8"
  machineImage: "capi-ubuntu-2204-kube-v1.31.8-2025-05-02"

  nodeGroups:
    - name: default-md-0
      machineCount: 2
      machineFlavor: l2.tiny

  addons:
    cni:
      type: cilium
      cilium:
        release:
          values:
            gatewayAPI:
              enabled: true