namePrefix: worker-
namespace: clusters

resources:
  - ../../../components/cluster

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: cluster-values
    files:
      - values.yaml=capi-values.yaml

secretGenerator:
  - name: cluster-api-server-fip
    files:
      - values.yaml=./secrets/api-server-fip.yaml.encrypted
  - name: cluster-app-creds
    files:
      - values.yaml=./secrets/app-creds.yaml.encrypted


# We still need to patch the HelmRelease's releaseName and valuesFrom
patches:
  - target:
      kind: HelmRelease
      name: cluster
    patch: |-
      - op: replace
        path: /spec/releaseName
        value: worker
      - op: add
        path: /spec/valuesFrom/-
        value:
          kind: ConfigMap
          name: cluster-values
      - op: add
        path: /spec/valuesFrom/-
        value:
          kind: Secret
          name: worker-cluster-api-server-fip
      - op: add
        path: /spec/valuesFrom/-
        value:
          kind: Secret
          name: worker-cluster-app-creds

configurations:
  - kustomizeconfig.yaml