---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: openstack-cluster
  namespace: capi-self
spec:
  chart: stfc-cloud-openstack-cluster
  version: 1.4.0
  sourceRef:
    kind: HelmRepository
    name: stfc-cloud-charts
  interval: 1h
