namespace: clusters
resources:
  - helmrelease.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: capi-cluster-base-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml