namePrefix: management-

resources:
  - ../../components/cluster
  - ./capi-cluster

# We still need to patch the HelmRelease's releaseName and valuesFrom
patches:
  - target:
      kind: HelmRelease
      name: cluster
    patch: |-
      - op: replace
        path: /spec/releaseName
        value: management
      - op: add
        path: /spec/valuesFrom/-
        value:
          kind: ConfigMap
          name: cluster-values
      - op: add
        path: /spec/valuesFrom/-
        value:
          kind: Secret
          name: cluster-api-server-fip
      - op: add
        path: /spec/valuesFrom/-
        value:
          kind: Secret
          name: cluster-app-creds

configMapGenerator:
  - name: cluster-values
    files:
      - values.yaml=capi-values.yaml

secretGenerator:
  - name: cluster-api-server-fip
    files:
      - values.yaml=./secrets/api-sever-fip.enc.yaml
  - name: cluster-app-creds
    files:
      - values.yaml=./secrets/app-creds.enc.yaml