nameReference:
- kind: ConfigMap
  version: v1
  fieldSpecs:
  - path: spec/valuesFrom/name
    kind: HelmRelease
- kind: Secrets
  version: v1
  fieldSpecs:
  - path: spec/valuesFrom/name
    kind: HelmRelease