resources:
  - namespace.yaml
  - configmap.yaml
  - helmrepository.yaml
  - helmchart.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: cluster-api-operator-base-config
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml