namespace: capi-operator-system
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmchart.yaml
  - helmrelease.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: cluster-api-operator-base-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml