---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: management-cluster-controller
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: fluxcd-sops-key
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: clusters/management/infra
  prune: true
  wait: true