---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux
  namespace: flux-system
spec:
  chartRef:
    kind: HelmChart
    name: flux2
  releaseName: flux
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  driftDetection:
    mode: enabled
  interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: flux-base-config
    - kind: ConfigMap
      name: flux-cluster-config
      optional: true