namespace: cert-manager
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmchart.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: cert-manager-base-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml