openstack-cluster:
    apiServer:
        floatingIP: ENC[AES256_GCM,data:ALPd+50wjF30rrg96PB8,iv:ivNt6YHrxt076V/TG8sF33jkBwfndhV0k0aWIttN0zM=,tag:1nSd5eHIThHHufsBmvKwhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10enjs5rrv2l2ka69hgyc7dmje8zlllec7gyj3esxuk5k42crzp6swhyskr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbXVVYUxvSzRwQWJOeFNF
            bE5qV0xDM0tBNTlMbDdkTWdnVlBYYTIvU2xzCkY4Tlh6ZitOeVFXZ0tLMWtjdmcv
            c09EaEpURzE4SVhZQlRpajdwREtMK0UKLS0tIDgyM3dtb2t3TXJjVldSVDZkMUZY
            Y2kzUkQ0cy9DSlExNWVjYy9uTEltdzAKRPKMbbiNJlcD7gn+p5dwF/11Rvr7NyiD
            aOwcteqPhLswyoT6m5ad/6KlVBkzzdI4fCnHefPk4eFV9b9OYCcBzw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12khufkd7z25eqgpjjyy0zcrq6kpjxzekmff5zhq7q54tajm4e58qul35x0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWXlvaEdsalJSemVoWm9V
            NlBDSDBlR1VPOFNzMTdyNU9UY1U5MmFRU21RCkpPQXJ0dVhIOE1zWVFEdTMrWUVK
            Z2taanRlNmphbHpJYlpCdGxiWnlFVGcKLS0tIG51QUJmb3o4MGdZcThXeWFDa2hZ
            TEo3c0FvbStQejhXa2RDNWt0SVlmM0EKDwNrWh89iJs4YMWXWs1eBjzwbW8p/Pdp
            Cv+LwLBA3TPnYk0w9ggY6zggAovLnSsac8IPOMWWlrsdmfj8HAY9LQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-19T11:48:08Z"
    mac: ENC[AES256_GCM,data:Ws3g8www5miJRkBP5rF/uyPXg+gRgfcgNGL5iXOiPIf69eExPKU/z7CBeRouQEQM3zrjkEpoF+UJTJYVaLwQTkIe0hgDCI38LNDV+mI5P4BSOLGicA6Lj1PdntYLUjmVCc99Zka1bji/EtfXTPNeqMQuq3VOvfSS3ytKlF1j3QI=,iv:khsaj6X3LVUF5kMPWcUYFrbnzs5nF0ymbzitsh8QImM=,tag:YKAmXwuyYCqNzSqTk8Whfw==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.8.1
