clouds:
    openstack:
        auth:
            auth_url: ENC[AES256_GCM,data:fg5ndGtBSxH3QOuSXGZzSYvHRNH0jZlfax3vrm7WfVgmgRNHfg==,iv:FFV+UxhygF1pE8+dGuOoo0+tV+8DQgsa0Eervjjn2rk=,tag:7Qcei+k8Zeun2t+SIjpHug==,type:str]
            application_credential_id: ENC[AES256_GCM,data:ksY9a4TKeiDZmSMe7pixe9YKR+LG2JYWBn9/3gC11no=,iv:ADMwhrppzWwqw0z7YBFxJu+JyY1wVFPsemhm/FsNcOE=,tag:bviTwp4vihb4l1Me5Q1s2g==,type:str]
            application_credential_secret: ENC[AES256_GCM,data:nEPToBDkLU2JByiY7E/iOG31uN3zRZuyI0LzOtWzk5PgvH2nWfYpVaSwZ60NjSf59Fkuy5j6I7lJTeIGFJKFnxBZ7X11rktkU2kC+6Il6Y3vxAFuG5I=,iv:/hToTsQ99nI5n+bC4/56D51tShiBvlRw/4yVVh7Fyiw=,tag:mbVlMTF2DxJqcL2/ZWXJfw==,type:str]
            project_id: ENC[AES256_GCM,data:YORZ+x+GM01cBM02XRc7yxV0rpSV55KmI2UCHTujjx4=,iv:ES1BbMfHg/z5x31t/JfHne/ZACHpdan0p4jpfXzjpLo=,tag:UCpseBXANHGjg0yeCtu+8g==,type:str]
        region_name: ENC[AES256_GCM,data:uG54vW5pqw2g,iv:0t5mSSXxO5NPqnZqb/SYjaMs3CLHthypBXwh0JxmTpo=,tag:JoR/a1bnjUUL/4EIS125Sw==,type:str]
        interface: ENC[AES256_GCM,data:Arjj4hUV,iv:WkvpuBN3/P95nsm1zEDHChME3gFG8PaTHtAQMbdIATg=,tag:Hi39LPUoxdPpSWJhaQ9/Sg==,type:str]
        identity_api_version: ENC[AES256_GCM,data:zw==,iv:PuVsCyVqBoDpYrqcF4veL87Ml+yeltU0eq5cGs2/LkU=,tag:EYdKcUrQtCfoLy78SgU/6Q==,type:int]
        auth_type: ENC[AES256_GCM,data:93Mf7BsTay0seygUaIY9lMgj0qXk+D0=,iv:ZNVYQvFwTnpwaycEBDD8w7pLHVb+RXbD4+ctH8U+s0U=,tag:fS8TmHCAIryPp5iuksLsZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10enjs5rrv2l2ka69hgyc7dmje8zlllec7gyj3esxuk5k42crzp6swhyskr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TjFIVUl0NnV0eW1RWEM0
            ODBCbXNBRTBEQkxKZmoyQmxVbWRKZUw1aWdZClZCOW5NZmk1ZXVTTm1uWWoybEpR
            VXE3OUxOd21iNGl1dXJXc28yK0ErYjQKLS0tIDZyRW5zb0d0VXYwRzBSQ1VpUHJw
            aStTem95QTVQWUFWM3ZOcW9nY1NmMEUKSLufsISwozBsSz1Uf7IiFV1y+aa/hpab
            mW+nzW5O179yJmDIZhtiO8pQbipCJJbLju70un/jYZFknG+32M3enw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12khufkd7z25eqgpjjyy0zcrq6kpjxzekmff5zhq7q54tajm4e58qul35x0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Z3NpTFVmSnB4dGU5bDEz
            QXh2OFBKMjl0NUtwSHl2cFMwSklMNFQ2MFFRClpTWDBFSm1zb0lTcnpnTVR4UUVH
            MVdXckl1czNxU1hzQldKd0dzRmFDNDgKLS0tIFViaTZoMWE5eUx3ckl4NDZEMFFz
            bU5yQXY3MG9IWUFOVlZmMWlXYUcyQlEKSKrmqALTrwNdmiDTSJ20XRuOQkykr525
            NchVW16D57oUkIAb2XKq7hFmK16OVQGTzltDstKqa3ljNs02C8JVGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-19T10:46:34Z"
    mac: ENC[AES256_GCM,data:dAXbRyyZC/t0RSq6F1gLppvvouZjBEyPKy9E1KbJdUbbw86y44RJqwLVvXV1glI37bIewFPEgyxMN7y8yrMbZ2SxS4BpIsgXj4RCewIgNKEcAjJuTAUMZut947uWBg5ASmMdAtYpZVw41hrHInSoewWyNJ64f7izbtcEWPG2Ihw=,iv:03MWlTVxlXnG4GxMMBWjWqzysEGxjRAwPa0QL2HNlDs=,tag:zvlVNqYIbID2YtHEHJD21Q==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.8.1
