clouds:
    openstack:
        auth:
            auth_url: ENC[AES256_GCM,data:57NYeBjPR3SfnvUQZfQKPTvvTcx8h9mwhif7AIAxaJ8KWBCneQ==,iv:Bqbw6s7Ght7UUqlc6DU7VvCqNc5Ih3si6k8IF0FmdPo=,tag:gHlwlMnFrsner+s6TilcTQ==,type:str]
            application_credential_id: ENC[AES256_GCM,data:NkQ/R8R9yezkBWOEXZypHDB1JzAmM/J8tpf4NExdVxU=,iv:dj9Ayjb/9QEt4XIqco9xot+arvqssHN01t4ZpNS96y8=,tag:BKe+mk48WLaxc253iKUuSw==,type:str]
            application_credential_secret: ENC[AES256_GCM,data:2H8A0bi84OWTED6lbfFxEEoIgoxTM6y5wvkeTVL+R3APDQWJi3BmHJ6eYAnAgt4Db1pdm+tsgtC/0ysjXMi4kohbQClI32KGZo3el9++gs2Km7k3zkk=,iv:/U07gjJQoyHg8rJnAtSey64UfV5/DNdqbsFfmhLDlAo=,tag:SKCEcVT5T36xsQHPBrGiyw==,type:str]
            project_id: ENC[AES256_GCM,data:sXLndMTTRxJxCi3xtt4ovwvlMTDFUE452FRJWNQWbnc=,iv:2nzXIJsthqX+IB1xVQZ+0YKv1IzMS8G/gjag2geAg3A=,tag:qCyo06h3U56y5qPxDieXvA==,type:str]
        region_name: ENC[AES256_GCM,data:OwUvjpy5B61h,iv:yugov17Wp7iYsf/NJvy57emPXHerQh3lgvxuPfP/6gk=,tag:Q2nvOkWAfKMOo6kDI+BYrw==,type:str]
        interface: ENC[AES256_GCM,data:EvXV9pdz,iv:X5uqqiI0jwneEpdtEXF1AhIMwfYBrBuunktM+26qp30=,tag:a3Sd7GuXC1c2ztwxh0aeUQ==,type:str]
        identity_api_version: ENC[AES256_GCM,data:OA==,iv:FHNg1ODJB0ROhNXi16kmjeondFikR0G/+9qwrmMDYYU=,tag:1Tny5yWW7+qTXYSwwNXoug==,type:int]
        auth_type: ENC[AES256_GCM,data:ii6vlP2cWzI/eA4Q56PuuSx4yRVDW0o=,iv:IYR5aPUvcCwVYrZVRBqgxZ+miZGWYRPrzNWnjCH94HM=,tag:AI/CEvJYU+xD6xvGtvTENQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10enjs5rrv2l2ka69hgyc7dmje8zlllec7gyj3esxuk5k42crzp6swhyskr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TjFIVUl0NnV0eW1RWEM0
            ODBCbXNBRTBEQkxKZmoyQmxVbWRKZUw1aWdZClZCOW5NZmk1ZXVTTm1uWWoybEpR
            VXE3OUxOd21iNGl1dXJXc28yK0ErYjQKLS0tIDZyRW5zb0d0VXYwRzBSQ1VpUHJw
            aStTem95QTVQWUFWM3ZOcW9nY1NmMEUKSLufsISwozBsSz1Uf7IiFV1y+aa/hpab
            mW+nzW5O179yJmDIZhtiO8pQbipCJJbLju70un/jYZFknG+32M3enw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12khufkd7z25eqgpjjyy0zcrq6kpjxzekmff5zhq7q54tajm4e58qul35x0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Z3NpTFVmSnB4dGU5bDEz
            QXh2OFBKMjl0NUtwSHl2cFMwSklMNFQ2MFFRClpTWDBFSm1zb0lTcnpnTVR4UUVH
            MVdXckl1czNxU1hzQldKd0dzRmFDNDgKLS0tIFViaTZoMWE5eUx3ckl4NDZEMFFz
            bU5yQXY3MG9IWUFOVlZmMWlXYUcyQlEKSKrmqALTrwNdmiDTSJ20XRuOQkykr525
            NchVW16D57oUkIAb2XKq7hFmK16OVQGTzltDstKqa3ljNs02C8JVGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-19T09:53:51Z"
    mac: ENC[AES256_GCM,data:yLeZ6IwnWHqPlKVVzNhxmdNgcgVOAZAcuji8coTk1dJ/9pl5zhZfC43vZ5FVU3Eyt392az6vo+gXAH5qbojF+19YWl5sDGsmUXduNxu7KtQ5JPEY8us5ZT2ehNvTQELoPbF1rpCE1JFJOih/pKY/rN31Z+zNJ082zDfSzyJuQls=,iv:BMaD7TVmmKuSIIO1LXd2EA1PdVtzergw5JwCodl9rqw=,tag:GSeaZUXyTUfWVBMM0joHaA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.8.1
